CREATE LOGIN [IIS APPPOOL\Backend] FROM WINDOWS;

USE OrdersDb;
CREATE USER [IIS APPPOOL\Backend] FOR LOGIN [IIS APPPOOL\Backend];
ALTER ROLE db_datareader ADD MEMBER [IIS APPPOOL\Backend];
ALTER ROLE db_datawriter ADD MEMBER [IIS APPPOOL\Backend];

USE UserDb;
CREATE USER [IIS APPPOOL\Backend] FOR LOGIN [IIS APPPOOL\Backend];
ALTER ROLE db_datareader ADD MEMBER [IIS APPPOOL\Backend];
ALTER ROLE db_datawriter ADD MEMBER [IIS APPPOOL\Backend];
